In [9]:
from slicing_inference import sahi_slicing_inference
from PIL import Image
import numpy as np
from imageutils import resize_img
import torch

In [2]:
image_path=r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg"
result = sahi_slicing_inference(image_path, scale_factor=4, confidence_threshold=0.9)

Performing prediction on 8 number of slices.
Object found -> bbox:  [290.67914 512.6692  333.07648 667.62524]
Object found -> bbox:  [582.70105 424.4006  594.5731  459.0754 ]
Object found -> bbox:  [589.0596  724.09076 616.5419  758.63434]
Object found -> bbox:  [587.81854 379.13177 626.6871  393.10223]
Object found -> bbox:  [490.6183  390.73325 506.50665 440.93832]
Object found -> bbox:  [466.03265 451.71088 477.8919  499.84845]
Object found -> bbox:  [425.17847 384.7847  457.38507 396.3138 ]
Object found -> bbox:  [490.50882 446.50525 499.03775 469.39404]
Object found -> bbox:  [456.107   395.19382 464.78827 424.93655]
Object found -> bbox:  [410.62286 390.77545 426.52258 440.72778]
Object found -> bbox:  [386.14456 450.70663 397.69846 499.03232]
Object found -> bbox:  [345.39575 384.60666 377.41205 396.21536]
Object found -> bbox:  [387.42926 388.20602 395.8802  427.38083]
Object found -> bbox:  [410.3145  446.34796 419.13892 469.3927 ]
Object found -> bbox:  [376.37534 394.4052  3

In [4]:
print(result['n_obj'])
print(result['bboxes'])
print(result['scores'])
print(result["resized_image_size"])

13
[(905.6791381835938, 512.669189453125, 948.0764770507812, 667.625244140625), (1093.2074890136719, 908.5266723632812, 1214.3609619140625, 1034.5568237304688), (1302.7169189453125, 848.1006164550781, 1327.792308807373, 876.3728942871094), (1720.6182861328125, 390.7332458496094, 1736.5225830078125, 440.9383239746094), (1197.7010498046875, 424.4006042480469, 1209.5731201171875, 459.0754089355469), (1696.0326538085938, 450.7066345214844, 1707.8919067382812, 499.84844970703125), (1196.3193359375, 915.290771484375, 1363.2810363769531, 1033.8690185546875), (1203.8644409179688, 723.9636764526367, 1231.5418701171875, 758.6343383789062), (1655.178466796875, 384.6066589355469, 1687.4120483398438, 396.3138122558594), (1720.3145141601562, 446.34796142578125, 1729.138916015625, 469.39404296875), (1202.8185424804688, 379.13177490234375, 1241.6870727539062, 393.10223388671875), (1697.4292602539062, 388.2060241699219, 1705.8801879882812, 427.3808288574219), (1686.1069946289062, 394.40521240234375, 16

In [45]:
result['prediction'].export_visuals(export_dir="demo_data/", hide_labels=True,)

In [2]:
import math
p = 110
round(math.sqrt(p / 25), 1)

2.1

In [16]:
image_path=r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg"
image = Image.open(image_path).convert("RGB")
print(image.size)
image = Image.fromarray(np.uint8(image)).convert('RGB')
print(image.size)
w, h = image.size
print(h)
print(w)
# Init output image.
# image_out = np.empty((n_rows, n_cols, 3))

(8313, 5513)
(8313, 5513)
5513
8313


In [23]:
image = np.asarray(Image.open(image_path))
h, w, _ = image.shape
print(h)
print(w)

5513
8313


In [3]:
SAHI_ACTIVATION_THRESHOLD = 4
IMG_DIM = 768
SAHI_ADAPTIVE_RESIZING = True

In [4]:
image_path=r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg"
image = Image.open(image_path).convert("RGB")\

w, h = image.size
print(w)
print(h)

if w * h > SAHI_ACTIVATION_THRESHOLD * IMG_DIM * IMG_DIM:
    if SAHI_ADAPTIVE_RESIZING == True:
        p = (w * h) // (IMG_DIM * IMG_DIM)
        if p > 6:
            SAHI_SCALE_DOWN_FACTOR = round(math.sqrt(p / 25), 1)
        else:
            SAHI_SCALE_DOWN_FACTOR = 1

print(f"SAHI_SCALE_DOWN_FACTOR : {SAHI_SCALE_DOWN_FACTOR}")

8313
5513
SAHI_SCALE_DOWN_FACTOR : 1.8


In [7]:
h_r = h//SAHI_SCALE_DOWN_FACTOR
w_r = w//SAHI_SCALE_DOWN_FACTOR

h_r, w_r = map(int, (h_r, w_r))
print(h_r)
print(w_r)

3062
4618


In [6]:
resized_image = resize_img(image= image, height= h_r, width=w_r)
resized_image = Image.fromarray(np.uint8(resized_image)).convert('RGB')

0
0
0
1


In [14]:
scores = torch.Tensor([0.0855, 0.855, 0.0855, 0.0855, 0.855, 0.0855])
scores

tensor([0.0855, 0.8550, 0.0855, 0.0855, 0.8550, 0.0855])

In [15]:
acceptable_scores_mask = np.array([i > 0.8 for i in scores])
acceptable_scores_mask

array([False,  True, False, False,  True, False])

In [17]:
a = np.array([1,2,3,4,5,6])
a = a[acceptable_scores_mask]
a

array([2, 5])