In [1]:
import os, math
from slicing_inference import sahi_slicing_inference
from inference_modular import ship_detection, ship_detection_bulk
from PIL import Image 
import numpy as np
from imageutils import resize_img
import torch

SyntaxError: invalid syntax (inference_modular.py, line 380)

In [2]:
image_path=r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg"
image_path=r"D:\NLP 1\Sat_object_detection\inference_images\dd4ffcb5c.jpg"

image = Image.open(image_path).convert("RGB")

# model = torch.load('models/best_model.pth', map_location = 'cuda')

In [3]:
bbox_coord = [53.996172, 16.951560, 54.010077, 16.963793]
result = ship_detection_sahi(image=image, bbox_coord_wgs84=bbox_coord)

Performing prediction on 1 number of slices.
Object found -> bbox:  [ 73.13797  639.82117  124.770706 741.1826  ]
Object found -> bbox:  [ 37.490547 137.97885   99.83393  229.94489 ]
Object found -> bbox:  [579.8303  552.79254 610.90784 606.02045]


In [4]:
result
# result['prediction'].export_visuals(export_dir="demo_data/", hide_labels=True,)

{'res_object': <sahi.prediction.PredictionResult at 0x22e7fd434d0>,
 'n_obj': 3,
 'bboxes': array([[ 73.13797 , 639.82117 , 124.770706, 741.1826  ],
        [ 37.490547, 137.97885 ,  99.83393 , 229.94489 ],
        [579.8303  , 552.79254 , 610.90784 , 606.02045 ]], dtype=float32),
 'scores': array([0.99949455, 0.9990532 , 0.99712497], dtype=float32),
 'sahi_scaled_down_image': <PIL.Image.Image image mode=RGB size=768x768>,
 'ships_coord': [(53.997963614676, 16.962558580268),
  (53.997415162024, 16.95449021554),
  (54.006951436265, 16.960789009952)],
 'ships_length': [205.2, 202.4, 111.7],
 'ships_bbox_dimensions': [(179.5, 99.4), (162.9, 120.1), (94.3, 59.8)]}

In [31]:
import os
path = r"D:\NLP 1\Sat_object_detection\inference_images"
# raw_path = r"{0}".format(path)
# path.encode()
# os.path.exists(path)

In [16]:
image_ext = ('.jpg','.jpeg', '.png', '.jp2', '.jfif', '.pjpeg', '.webp', '.tiff', '.tif')
filename = r"D:\NLP1\Sat_object_detection\inference_images\fsdf.png"
# filename = fr"{filename}"
filename.endswith(image_ext)

True

In [23]:
mask_filename = "{}_pred{}".format(os.path.splitext(filename)[0], os.path.splitext(filename)[1])
mask_filename

'D:\\NLP1\\Sat_object_detection\\inference_images\\fsdf_pred.png'

In [26]:
size = os.path.getsize(r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg")
size

1262285

In [33]:
stat = os.stat(r"D:\NLP 1\Sat_object_detection\debug_images\2.jpg")
stat.st_size


1262285

In [4]:
from exifread import process_file
def get_image_dimensions(file_path):
    with open(file_path, 'rb') as f:
        tags = process_file(f, details=True)
        return tags

In [7]:
image_path = r"D:\NLP 1\Sat_object_detection\inference_images\2.jpg"
d = get_image_dimensions(image_path)
d

NameError: name 'get_image_dimensions' is not defined

In [5]:
from get_image_size import *

In [86]:
from PIL import Image
from time import time

t1 = time()
counter = 0
images_data = []
images_dir = r"D:\NLP 1\Sat_object_detection\inference_images"
# images_dir = r"D:\NLP 1\Sat_object_detection\large_images"
image_ext = ('.jpg','.jpeg', '.png', '.jp2', '.jfif', '.pjpeg', '.webp', '.tiff', '.tif')
for filename in os.listdir(images_dir):
    if filename.endswith(image_ext):
        # print(filename)
        img = filename
        img_mask = "{}_pred{}".format(os.path.splitext(filename)[0], os.path.splitext(filename)[1])
        img_size = Image.open(os.path.join(images_dir, filename)).size
        images_data.append([img, img_mask, img_size])
        counter += 1
print(counter)
print(images_data)

model_input_dim = 768
for img in images_data:
    w, h = img[2]
    p = (w * h) // (model_input_dim * model_input_dim)
    if p > 10:
        img_sahi_scale_down_factor = int(round(math.sqrt(p / 20), 0))
    else:
        img_sahi_scale_down_factor = 1
    img.append(img_sahi_scale_down_factor)
print(images_data)

organized_images_by_scale_down_factor = {}
for sublist in images_data:
    last_element = sublist[-1]
    if last_element not in organized_images_by_scale_down_factor:
        organized_images_by_scale_down_factor[last_element] = []
    organized_images_by_scale_down_factor[last_element].append(sublist)

print(organized_images_by_scale_down_factor)
print(f"{time()-t1:.4f}")

132
[['011409565.jpg', '011409565_pred.jpg', (768, 768)], ['012473874.jpg', '012473874_pred.jpg', (768, 768)], ['01f13f599.jpg', '01f13f599_pred.jpg', (768, 768)], ['032610514.jpg', '032610514_pred.jpg', (768, 768)], ['037367901.jpg', '037367901_pred.jpg', (768, 768)], ['03a75a583.jpg', '03a75a583_pred.jpg', (768, 768)], ['041409351.jpg', '041409351_pred.jpg', (768, 768)], ['058358044.jpg', '058358044_pred.jpg', (768, 768)], ['065080198.jpg', '065080198_pred.jpg', (768, 768)], ['078464555.jpg', '078464555_pred.jpg', (768, 768)], ['08229754b.jpg', '08229754b_pred.jpg', (768, 768)], ['084269309.jpg', '084269309_pred.jpg', (768, 768)], ['0aba8fa6f.jpg', '0aba8fa6f_pred.jpg', (768, 768)], ['0b7359c38.jpg', '0b7359c38_pred.jpg', (768, 768)], ['0c0d90d8d.jpg', '0c0d90d8d_pred.jpg', (768, 768)], ['0c24ec954.jpg', '0c24ec954_pred.jpg', (768, 768)], ['0e40b3a5b.jpg', '0e40b3a5b_pred.jpg', (768, 768)], ['0ec10921f.jpg', '0ec10921f_pred.jpg', (768, 768)], ['1.jpg', '1_pred.jpg', (2000, 1467)], ['

In [89]:
for i in organized_images_by_scale_down_factor.keys():
    print(i)

1
2


In [85]:
model_input_dim = 768
for img in images_data:
    w, h = img[2]
    p = (w * h) // (model_input_dim * model_input_dim)
    if p > 10:
        img_sahi_scale_down_factor = int(round(math.sqrt(p / 20), 0))
    else:
        img_sahi_scale_down_factor = 1
    img.append(img_sahi_scale_down_factor)
print(images_data)

[['011409565.jpg', '011409565_pred.jpg', (768, 768), 1, 1], ['012473874.jpg', '012473874_pred.jpg', (768, 768), 1, 1], ['01f13f599.jpg', '01f13f599_pred.jpg', (768, 768), 1, 1], ['032610514.jpg', '032610514_pred.jpg', (768, 768), 1, 1], ['037367901.jpg', '037367901_pred.jpg', (768, 768), 1, 1], ['03a75a583.jpg', '03a75a583_pred.jpg', (768, 768), 1, 1], ['041409351.jpg', '041409351_pred.jpg', (768, 768), 1, 1], ['058358044.jpg', '058358044_pred.jpg', (768, 768), 1, 1], ['065080198.jpg', '065080198_pred.jpg', (768, 768), 1, 1], ['078464555.jpg', '078464555_pred.jpg', (768, 768), 1, 1], ['08229754b.jpg', '08229754b_pred.jpg', (768, 768), 1, 1], ['084269309.jpg', '084269309_pred.jpg', (768, 768), 1, 1], ['0aba8fa6f.jpg', '0aba8fa6f_pred.jpg', (768, 768), 1, 1], ['0b7359c38.jpg', '0b7359c38_pred.jpg', (768, 768), 1, 1], ['0c0d90d8d.jpg', '0c0d90d8d_pred.jpg', (768, 768), 1, 1], ['0c24ec954.jpg', '0c24ec954_pred.jpg', (768, 768), 1, 1], ['0e40b3a5b.jpg', '0e40b3a5b_pred.jpg', (768, 768), 1, 

In [79]:
for img in images_data:
    if img[3] != 1:
        print(img)

['2.jpg', '2_pred.jpg', (8313, 5513), 2]
['2_1.jpg', '2_1_pred.jpg', (5513, 5513), 2]


In [80]:
organized_images_by_scale_down_factor = {}
for sublist in images_data:
    last_element = sublist[-1]
    if last_element not in organized_images_by_scale_down_factor:
        organized_images_by_scale_down_factor[last_element] = []
    organized_images_by_scale_down_factor[last_element].append(sublist)

In [76]:
organized_images_by_scale_down_factor

{1: [['011409565.jpg', '011409565_pred.jpg', (768, 768), 1],
  ['012473874.jpg', '012473874_pred.jpg', (768, 768), 1],
  ['01f13f599.jpg', '01f13f599_pred.jpg', (768, 768), 1],
  ['032610514.jpg', '032610514_pred.jpg', (768, 768), 1],
  ['037367901.jpg', '037367901_pred.jpg', (768, 768), 1],
  ['03a75a583.jpg', '03a75a583_pred.jpg', (768, 768), 1],
  ['041409351.jpg', '041409351_pred.jpg', (768, 768), 1],
  ['058358044.jpg', '058358044_pred.jpg', (768, 768), 1],
  ['065080198.jpg', '065080198_pred.jpg', (768, 768), 1],
  ['078464555.jpg', '078464555_pred.jpg', (768, 768), 1],
  ['08229754b.jpg', '08229754b_pred.jpg', (768, 768), 1],
  ['084269309.jpg', '084269309_pred.jpg', (768, 768), 1],
  ['0aba8fa6f.jpg', '0aba8fa6f_pred.jpg', (768, 768), 1],
  ['0b7359c38.jpg', '0b7359c38_pred.jpg', (768, 768), 1],
  ['0c0d90d8d.jpg', '0c0d90d8d_pred.jpg', (768, 768), 1],
  ['0c24ec954.jpg', '0c24ec954_pred.jpg', (768, 768), 1],
  ['0e40b3a5b.jpg', '0e40b3a5b_pred.jpg', (768, 768), 1],
  ['0ec1092

In [28]:
for r, d, f in a:
    print(r, d, f)

D:\NLP 1\Sat_object_detection\inference_images ['aaa'] ['011409565.jpg', '012473874.jpg', '01f13f599.jpg', '032610514.jpg', '037367901.jpg', '03a75a583.jpg', '041409351.jpg', '058358044.jpg', '065080198.jpg', '078464555.jpg', '08229754b.jpg', '084269309.jpg', '0aba8fa6f.jpg', '0b7359c38.jpg', '0c0d90d8d.jpg', '0c24ec954.jpg', '0e40b3a5b.jpg', '0ec10921f.jpg', '1.jpg', '12572286c.jpg', '14013864b.jpg', '18609713e.jpg', '1b5fd69bc.jpg', '1ca44d679.jpg', '1d0f400ee.jpg', '1_2.jpg', '1_3.jpg', '2.jpg', '26095039a.jpg', '26823809a.jpg', '2bf540ab6.jpg', '2c65c3125.jpg', '2cb5d47a2.jpg', '2d1a6f1d7.jpg', '2d1b074cb.jpg', '2ec80a085.jpg', '2f444438d.jpg', '2_1.jpg', '2_2.jpg', '31745469d.jpg', '33925893c.jpg', '34899620c.jpg', '38168248b.jpg', '38237658a.jpg', '38988163c.jpg', '3b0d1d4b2.jpg', '3b1539a5d.jpg', '3b1554d64.jpg', '3b3ed2440.jpg', '42648574d.jpg', '43347542c.jpg', '44071141e.jpg', '44175789d.jpg', '44432557e.jpg', '44584888f.jpg', '44618001a.jpg', '46653100b.jpg', '52297959b.jpg'

In [12]:
d = {"a": 1, "b": 2}
print(d.get("c"))

None


In [51]:
b

NameError: name 'b' is not defined

In [1]:
from inference_modular import ship_detection, ship_detection_bulk
# images_path = r"D:\NLP 1\Sat_object_detection\inference_images"
images_path = r"D:\NLP 1\Sat_object_detection\debug_images_2"
coord = {"0c0d90d8d.jpg": [58.4893887115,23.6396684794,58.4961460224,23.6487324542]}

result = ship_detection_bulk(images_dir=images_path, bbox_coord_wgs84=coord)

D:\NLP 1\venv\Lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
D:\NLP 1\venv\Lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pyto

Processing 03a75a583.jpg
Performing prediction on 1 number of slices.
bboxes.dim():  1
tensor([])
Processing 08229754b.jpg
Performing prediction on 1 number of slices.
Object found -> bbox:  [434.6351  356.14618 471.4752  481.77582]
Object found -> bbox:  [748.93353 431.21533 767.94855 471.54468]
bboxes.dim():  2
tensor([[434.6351, 356.1462, 471.4752, 481.7758],
        [748.9335, 431.2153, 767.9485, 471.5447]])
434 356 471 481
748 431 767 471
Processing 0b7359c38.jpg
Performing prediction on 1 number of slices.
Object found -> bbox:  [ 25.5195  414.79556 415.13986 478.85983]
bboxes.dim():  2
tensor([[ 25.5195, 414.7956, 415.1399, 478.8598]])
25 414 415 478
Processing 0c0d90d8d.jpg
Performing prediction on 1 number of slices.
Object found -> bbox:  [593.7077   45.92871 753.17255 254.45227]
Object found -> bbox:  [620.5995  627.19763 637.94653 635.86365]
Object found -> bbox:  [180.73062 636.78705 194.8421  644.33075]
bboxes.dim():  2
tensor([[593.7077,  45.9287, 753.1725, 254.4523],
  

error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'putText'
> Overload resolution failed:
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type
>  - Can't parse 'org'. Sequence item with index 0 has a wrong type


In [14]:
result["0c0d90d8d.jpg"]

{'n_obj': 4,
 'bboxes': array([[593.7077 ,  45.92871, 753.17255, 254.45227],
        [620.5995 , 627.19763, 637.94653, 635.86365],
        [180.73062, 636.78705, 194.8421 , 644.33075],
        [119.95   , 644.51044, 133.83653, 653.96564]], dtype=float32),
 'scores': array([0.9998567 , 0.9744727 , 0.9333982 , 0.88371474], dtype=float32),
 'sahi_scaled_down_image': <PIL.Image.Image image mode=RGB size=768x768>,
 'ships_coord': [(58.495314029591, 23.641441035159),
  (58.494925421619, 23.647121835915),
  (58.491040965183, 23.647228387887),
  (58.490505192283, 23.647330819514)],
 'ships_length': [308.8, 19.2, 16.0, 17.5],
 'ships_bbox_dimensions': [(273.7, 142.9),
  (15.5, 11.4),
  (12.6, 9.9),
  (12.4, 12.4)]}

In [1]:
from PIL import Image
import numpy as np
from imageutils import resize_img

factor = 3
image_path = r"D:\NLP 1\Sat_object_detection\inference_images\2.jpg"
image = Image.open(image_path)
w, h= image.size
resized_img = resize_img(image, h/factor, w/factor)

In [2]:
resized_img = Image.fromarray(np.uint8(resized_img)).convert('RGB')


In [3]:
resized_img.show()